/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dashboard.Client.Form;

import InitialData.Department;
import InitialData.Municipality;
import InitialData.RegionAndPriceManagement;
import InitialData.SG;
import PackageManagement.ManagementsOfRegionsAndPrices;
import static dashboard.Client.Form.Buy.CodeRegion;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

/**
 *
 * @author bruce
 */
public class PackageQuotation extends javax.swing.JPanel {

    /**
     * Creates new form PackageQuotation
     */
    public PackageQuotation() {
        initComponents();
        // Crea los botones de opción
        initData();
    }

    public void initData(){
        for (int i = 0; i < SG.departments.getLength(); i++) {
            Department department = SG.departments.getDepartmentRecord(i);
            cboOriginDepartment.addItem("["+department.getCode()+"]"+department.getName());    
            cboDestinyDepartment.addItem(department.getName());  
        }
        
        for (int i = 0; i < SG.municipalities.getLength(); i++) {
            Municipality municipality = SG.municipalities.getMunicipalityRecord(i);
            cboMunicipalityOrigin.addItem("["+municipality.getCode()+"]"+municipality.getName());
            cboDestinyMunicipality.addItem(municipality.getName());
        }
        rdPegueño.setText("Pegueño: Q"+SG.getSTICKY_PACKAGE());
        rdMediano.setText("Mediano: Q"+SG.getMEDIUM_PACKAGE());
        rdGrande.setText("Grande: Q"+SG.getLARGE_PACKAGE());
        
/*        cboOriginDepartment.setSelectedIndex(-1);
        cboDestinyDepartment.setSelectedIndex(-1);
        cboMunicipalityOrigin.setSelectedIndex(-1);
        cboDestinyMunicipality.setSelectedIndex(-1);*/
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JLabel();
        txtUserName1 = new javax.swing.JLabel();
        cboOriginDepartment = new javaswing.controls.Combobox();
        txtUserName2 = new javax.swing.JLabel();
        cboDestinyDepartment = new javaswing.controls.Combobox();
        cboMunicipalityOrigin = new javaswing.controls.Combobox();
        cboDestinyMunicipality = new javaswing.controls.Combobox();
        txtNumberOfPackage = new javaswing.controls.TextField();
        txtUserName3 = new javax.swing.JLabel();
        rdPegueño = new javax.swing.JRadioButton();
        rdMediano = new javax.swing.JRadioButton();
        rdGrande = new javax.swing.JRadioButton();
        cmdQuotation = new javaswing.controls.ButtonCustom();
        lblSubtotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBuyHere = new javax.swing.JLabel();
        txtUserName6 = new javax.swing.JLabel();
        rdServiceStandar = new javax.swing.JRadioButton();
        rdServiceSpecial = new javax.swing.JRadioButton();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(999, 621));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 72, 210));
        jLabel1.setText("Cotizacion de paquetes");

        txtUserName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(0, 0, 0));
        txtUserName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtUserName.setText("Cotizacion");

        txtUserName1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUserName1.setForeground(new java.awt.Color(0, 0, 0));
        txtUserName1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtUserName1.setText("Origen");

        cboOriginDepartment.setLabeText("Departamentos");
        cboOriginDepartment.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboOriginDepartmentItemStateChanged(evt);
            }
        });

        txtUserName2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUserName2.setForeground(new java.awt.Color(0, 0, 0));
        txtUserName2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtUserName2.setText("Destino");

        cboDestinyDepartment.setLabeText("Departamentos");
        cboDestinyDepartment.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboDestinyDepartmentItemStateChanged(evt);
            }
        });

        cboMunicipalityOrigin.setLabeText("Municipios");

        cboDestinyMunicipality.setLabeText("Municipios");

        txtNumberOfPackage.setLabelText("Número de paquetes");
        txtNumberOfPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberOfPackageActionPerformed(evt);
            }
        });

        txtUserName3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUserName3.setForeground(new java.awt.Color(0, 0, 0));
        txtUserName3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtUserName3.setText("Tamaño de paquetes");

        buttonGroup1.add(rdPegueño);
        rdPegueño.setText("Pegueño");
        rdPegueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdPegueñoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdMediano);
        rdMediano.setText("Mediano");

        buttonGroup1.add(rdGrande);
        rdGrande.setText("Grande");

        cmdQuotation.setText("Cotizar");
        cmdQuotation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmdQuotation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdQuotationActionPerformed(evt);
            }
        });

        lblSubtotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSubtotal.setForeground(new java.awt.Color(0, 0, 0));
        lblSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSubtotal.setText("El monto total a pagar es: Q0");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Payments.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Si deseas continuar con la compra da click:");

        jBuyHere.setForeground(new java.awt.Color(51, 51, 255));
        jBuyHere.setText("Aqui");
        jBuyHere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBuyHereMouseClicked(evt);
            }
        });

        txtUserName6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUserName6.setForeground(new java.awt.Color(0, 0, 0));
        txtUserName6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtUserName6.setText("TIpo de servicio:");

        buttonGroup2.add(rdServiceStandar);
        rdServiceStandar.setText("Servicio Estandar:: Q35");
        rdServiceStandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdServiceStandarActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdServiceSpecial);
        rdServiceSpecial.setText("Precio Especial: Q45");
        rdServiceSpecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdServiceSpecialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboOriginDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNumberOfPackage, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(cboMunicipalityOrigin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUserName2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboDestinyDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboDestinyMunicipality, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rdPegueño)
                        .addGap(18, 18, 18)
                        .addComponent(rdMediano)
                        .addGap(19, 19, 19)
                        .addComponent(rdGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtUserName3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdQuotation, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBuyHere))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rdServiceStandar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdServiceSpecial))
                    .addComponent(txtUserName6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 651, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUserName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboOriginDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboMunicipalityOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtUserName2)
                        .addGap(22, 22, 22)
                        .addComponent(cboDestinyDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboDestinyMunicipality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumberOfPackage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtUserName3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdPegueño)
                    .addComponent(rdMediano)
                    .addComponent(rdGrande))
                .addGap(18, 18, 18)
                .addComponent(txtUserName6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdServiceStandar)
                    .addComponent(rdServiceSpecial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdQuotation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jBuyHere))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );

        rdPegueño.getAccessibleContext().setAccessibleDescription("");
        rdPegueño.getAccessibleContext().setAccessibleParent(rdPegueño);
        rdMediano.getAccessibleContext().setAccessibleParent(rdPegueño);
        rdGrande.getAccessibleContext().setAccessibleParent(rdPegueño);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1156, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumberOfPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberOfPackageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberOfPackageActionPerformed

    private void rdPegueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdPegueñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdPegueñoActionPerformed

    private void jBuyHereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBuyHereMouseClicked
        // TODO add your handling code here:
        System.out.println("Aquiiiiiii");
    }//GEN-LAST:event_jBuyHereMouseClicked
    private static double specialPricePackage=0;
    private static double standarPricePackage=0;
    public static double subtotal= 0;
    private void cmdQuotationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdQuotationActionPerformed
        String DestinyDepartment= (String) cboDestinyDepartment.getSelectedItem();
        Department department = SG.departments.searchDeparmentName(DestinyDepartment);
        Boolean validation = false;
        double priceSize =0;
        
        try {
            if (rdPegueño.isSelected()) {
                priceSize=SG.STICKY_PACKAGE;
            }else if(rdMediano.isSelected()){
                priceSize=SG.MEDIUM_PACKAGE;
            }else if(rdGrande.isSelected()){
                priceSize=SG.LARGE_PACKAGE;
            }
            Integer numberofPackage= Integer.parseInt(txtNumberOfPackage.getText());
            String regionCodeDepartment = department.getCode();
            RegionAndPriceManagement regionAndPriceManagement = SG.managementsOfRegionsAndPrices.searchRegionCode(regionCodeDepartment);
            
            PackageManagement.Buy buy = new PackageManagement.Buy(SG.getClientFound(), 0);
            System.out.println(regionAndPriceManagement.getSpecialPrice()+"*"+priceSize+"*"+numberofPackage);
            
            if (rdServiceSpecial.isSelected()) {
                System.out.println("Susbtotal antes: "+subtotal);
                subtotal = buy.getPackageQuote(regionAndPriceManagement.getSpecialPrice(), priceSize, numberofPackage);
                System.out.println("Susbtotal despues: "+subtotal);
            }else if(rdServiceStandar.isSelected()){
                System.out.println("Susbtotal antes: "+subtotal);
                subtotal = buy.getPackageQuote(regionAndPriceManagement.getStandardPrice(), priceSize, numberofPackage);
                System.out.println("Susbtotal despues: "+subtotal);
            }
            
            lblSubtotal.setText("El monto total a pagar es: Q"+subtotal);
            
            
        } catch (Exception e) {
            System.out.println("Error de cotizar");
        }
    }//GEN-LAST:event_cmdQuotationActionPerformed

    private void rdServiceStandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdServiceStandarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdServiceStandarActionPerformed

    private void rdServiceSpecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdServiceSpecialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdServiceSpecialActionPerformed

    private void cboDestinyDepartmentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboDestinyDepartmentItemStateChanged
        for (int i = 0; i < SG.departments.getLength(); i++) {
            Department department = SG.departments.getDepartmentRecord(i);
            String regionCodeDepartment = department.getCode();
            RegionAndPriceManagement regionAndPriceManagement = SG.managementsOfRegionsAndPrices.searchRegionCode(regionCodeDepartment);
            if (cboDestinyDepartment.getSelectedItem().equals(department.getName())) {
                specialPricePackage = regionAndPriceManagement.getSpecialPrice();
                standarPricePackage = regionAndPriceManagement.getStandardPrice();
                CodeRegion= regionAndPriceManagement.getCode();
                rdServiceSpecial.setText("Servicio especial: "+specialPricePackage);
                rdServiceStandar.setText("Servicio estandar: "+standarPricePackage);
            }
        }
        
        Department department = SG.departments.getDepartmentRecord(cboDestinyDepartment.getSelectedIndex());
        cboDestinyMunicipality.removeAllItems();
        for (int i = 0; i < SG.municipalities.searchMunicipalityCode(String.valueOf(cboDestinyDepartment.getSelectedIndex())).size(); i++) {
            Municipality municipality = (Municipality) SG.municipalities.searchMunicipalityCode(String.valueOf(cboDestinyDepartment.getSelectedIndex())).get(i);
            cboDestinyMunicipality.addItem(municipality.getName());
            
        }
    }//GEN-LAST:event_cboDestinyDepartmentItemStateChanged

    private void cboOriginDepartmentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboOriginDepartmentItemStateChanged
        // TODO add your handling code here:
         Department department = SG.departments.getDepartmentRecord(cboOriginDepartment.getSelectedIndex());
        cboMunicipalityOrigin.removeAllItems();
        for (int i = 0; i < SG.municipalities.searchMunicipalityCode(String.valueOf(cboOriginDepartment.getSelectedIndex())).size(); i++) {
            Municipality municipality = (Municipality) SG.municipalities.searchMunicipalityCode(String.valueOf(cboOriginDepartment.getSelectedIndex())).get(i);
            cboMunicipalityOrigin.addItem(municipality.getName());
            
        }
    }//GEN-LAST:event_cboOriginDepartmentItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javaswing.controls.Combobox cboDestinyDepartment;
    private javaswing.controls.Combobox cboDestinyMunicipality;
    private javaswing.controls.Combobox cboMunicipalityOrigin;
    private javaswing.controls.Combobox cboOriginDepartment;
    private javaswing.controls.ButtonCustom cmdQuotation;
    private javax.swing.JLabel jBuyHere;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JRadioButton rdGrande;
    private javax.swing.JRadioButton rdMediano;
    private javax.swing.JRadioButton rdPegueño;
    private javax.swing.JRadioButton rdServiceSpecial;
    private javax.swing.JRadioButton rdServiceStandar;
    private javaswing.controls.TextField txtNumberOfPackage;
    private javax.swing.JLabel txtUserName;
    private javax.swing.JLabel txtUserName1;
    private javax.swing.JLabel txtUserName2;
    private javax.swing.JLabel txtUserName3;
    private javax.swing.JLabel txtUserName6;
    // End of variables declaration//GEN-END:variables
}
