/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dashboard.Client.Form;

import InitialData.Department;
import InitialData.Municipality;
import InitialData.RegionAndPriceManagement;
import InitialData.SG;
import PackageManagement.ManagementsOfRegionsAndPrices;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

/**
 *
 * @author bruce
 */
public class PackageQuotation extends javax.swing.JPanel {

    /**
     * Creates new form PackageQuotation
     */
    public PackageQuotation() {
        initComponents();
        // Crea los botones de opción
        initData();
    }

    public void initData(){
        for (int i = 0; i < SG.departments.getLength(); i++) {
            Department department = SG.departments.getDepartmentRecord(i);
            cboOriginDepartment.addItem("["+department.getCode()+"]"+department.getName());    
            cboDestinyDepartment.addItem(department.getName());  
        }
        
        for (int i = 0; i < SG.municipalities.getLength(); i++) {
            Municipality municipality = SG.municipalities.getMunicipalityRecord(i);
            cboMunicipalityOrigin.addItem("["+municipality.getCode()+"]"+municipality.getName());
            cboDestinyMunicipality.addItem(municipality.getName());
        }
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JLabel();
        txtUserName1 = new javax.swing.JLabel();
        cboOriginDepartment = new javaswing.controls.Combobox();
        txtUserName2 = new javax.swing.JLabel();
        cboDestinyDepartment = new javaswing.controls.Combobox();
        cboMunicipalityOrigin = new javaswing.controls.Combobox();
        cboDestinyMunicipality = new javaswing.controls.Combobox();
        txtNumberOfPackage = new javaswing.controls.TextField();
        txtUserName3 = new javax.swing.JLabel();
        rdPegueño = new javax.swing.JRadioButton();
        rdMediano = new javax.swing.JRadioButton();
        rdGrande = new javax.swing.JRadioButton();
        cmdQuotation = new javaswing.controls.ButtonCustom();
        txtSubtotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBuyHere = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(999, 621));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 72, 210));
        jLabel1.setText("Departamentos y municipios/Departamentos");

        txtUserName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(0, 0, 0));
        txtUserName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtUserName.setText("Cotizacion");

        txtUserName1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUserName1.setForeground(new java.awt.Color(0, 0, 0));
        txtUserName1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtUserName1.setText("Origen");

        cboOriginDepartment.setLabeText("Departamentos");

        txtUserName2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUserName2.setForeground(new java.awt.Color(0, 0, 0));
        txtUserName2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtUserName2.setText("Destino");

        cboDestinyDepartment.setLabeText("Departamentos");

        cboMunicipalityOrigin.setLabeText("Municipios");

        cboDestinyMunicipality.setLabeText("Municipios");

        txtNumberOfPackage.setLabelText("Número de paquetes");
        txtNumberOfPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberOfPackageActionPerformed(evt);
            }
        });

        txtUserName3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUserName3.setForeground(new java.awt.Color(0, 0, 0));
        txtUserName3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtUserName3.setText("Tamaño de paquetes");

        buttonGroup1.add(rdPegueño);
        rdPegueño.setText("Pegueño");
        rdPegueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdPegueñoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdMediano);
        rdMediano.setText("Mediano");

        buttonGroup1.add(rdGrande);
        rdGrande.setText("Grande");

        cmdQuotation.setText("Cotizar");
        cmdQuotation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmdQuotation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdQuotationActionPerformed(evt);
            }
        });

        txtSubtotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSubtotal.setForeground(new java.awt.Color(0, 0, 0));
        txtSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtSubtotal.setText("El monto total a pagar es: Q120");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Payments.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Si deseas continuar con la compra da click:");

        jBuyHere.setForeground(new java.awt.Color(51, 51, 255));
        jBuyHere.setText("Aqui");
        jBuyHere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBuyHereMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserName3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNumberOfPackage, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserName1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboOriginDepartment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboMunicipalityOrigin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rdPegueño)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdMediano)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdGrande, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUserName2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboDestinyDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(cboDestinyMunicipality, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(cmdQuotation, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(jBuyHere)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 593, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtUserName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboOriginDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtUserName2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboDestinyDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboMunicipalityOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDestinyMunicipality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNumberOfPackage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtUserName3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdPegueño)
                    .addComponent(rdMediano)
                    .addComponent(rdGrande))
                .addGap(18, 18, 18)
                .addComponent(cmdQuotation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jBuyHere))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );

        rdPegueño.getAccessibleContext().setAccessibleDescription("");
        rdPegueño.getAccessibleContext().setAccessibleParent(rdPegueño);
        rdMediano.getAccessibleContext().setAccessibleParent(rdPegueño);
        rdGrande.getAccessibleContext().setAccessibleParent(rdPegueño);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumberOfPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberOfPackageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberOfPackageActionPerformed

    private void rdPegueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdPegueñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdPegueñoActionPerformed

    private void jBuyHereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBuyHereMouseClicked
        // TODO add your handling code here:
        System.out.println("Aquiiiiiii");
    }//GEN-LAST:event_jBuyHereMouseClicked

    private void cmdQuotationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdQuotationActionPerformed
        // TODO add your handling code here:
        
        String DestinyDepartment= (String) cboDestinyDepartment.getSelectedItem();
        Department department = SG.departments.searchDeparmentName(DestinyDepartment);
        Boolean validation = false;
        double priceSize =0;
        try {
            if (rdPegueño.isSelected()) {
                priceSize=100;
            }else if(rdMediano.isSelected()){
                priceSize=150;
            }else if(rdGrande.isSelected()){
                priceSize= 200;
            }
            Integer numberofPackage= Integer.parseInt(txtNumberOfPackage.getText());
            String regionCodeDepartment = department.getCode();
            RegionAndPriceManagement regionAndPriceManagement = SG.managementsOfRegionsAndPrices.searchRegionCode(regionCodeDepartment);
            
            PackageManagement.Buy buy = new PackageManagement.Buy(SG.getClientFound(), 0);
            double subtotal =buy.getPackageQuote(regionAndPriceManagement.getStandardPrice(), priceSize, numberofPackage);
            
            txtSubtotal.setText("El monto total a pagar es: Q"+subtotal);
            
        } catch (Exception e) {
            System.out.println("Error de cotizar");
        }
    }//GEN-LAST:event_cmdQuotationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javaswing.controls.Combobox cboDestinyDepartment;
    private javaswing.controls.Combobox cboDestinyMunicipality;
    private javaswing.controls.Combobox cboMunicipalityOrigin;
    private javaswing.controls.Combobox cboOriginDepartment;
    private javaswing.controls.ButtonCustom cmdQuotation;
    private javax.swing.JLabel jBuyHere;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rdGrande;
    private javax.swing.JRadioButton rdMediano;
    private javax.swing.JRadioButton rdPegueño;
    private javaswing.controls.TextField txtNumberOfPackage;
    private javax.swing.JLabel txtSubtotal;
    private javax.swing.JLabel txtUserName;
    private javax.swing.JLabel txtUserName1;
    private javax.swing.JLabel txtUserName2;
    private javax.swing.JLabel txtUserName3;
    // End of variables declaration//GEN-END:variables
}
